# Set initialization file
https://cccma.gitlab.io/classic/makeInputFiles.html

Initialize the model for CLASSIC (CLASS+CTEM) run. Use the Paul's SnowMIP data to set the first soil layers proporties
and extend it.

In [1]:
# Env: sc2_v0

import xarray as xr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import proplot as pplt # New plot library (https://proplot.readthedocs.io/en/latest/)
pplt.rc['savefig.dpi'] = 300 # 1200 is too big! #https://proplot.readthedocs.io/en/latest/basics.html#Creating-figures

In [2]:
exp = 'STD_1000'
site = 'cdp'

path_in = '/home/lalandmi/eccc/SnowC2-CLASSIC-2D-model-private/inputFiles/SnowMIP/'+site # example file
path_out = '/home/lalandmi/eccc/SnowC2-CLASSIC-2D-model-private/inputFiles/SnowMIP/'+site

In [3]:
ds = xr.open_dataset(path_in+'/cdp_init_run_DEF_2D.nc')
ds.load()

<xarray.Dataset> Size: 11kB
Dimensions:            (tile: 1, lat: 1, lon: 1, icp1: 6, layer: 20, ic: 5,
                        icc: 12, iccp1: 13, iccp2: 14, slope: 8)
Coordinates:
  * ic                 (ic) int32 20B 1 2 3 4 5
  * icc                (icc) int32 48B 1 2 3 4 5 6 7 8 9 10 11 12
  * iccp1              (iccp1) int32 52B 1 2 3 4 5 6 7 8 9 10 11 12 13
  * iccp2              (iccp2) int32 56B 1 2 3 4 5 6 7 8 9 10 11 12 13 14
  * icp1               (icp1) int32 24B 1 2 3 4 5 6
  * slope              (slope) int32 32B 1 2 3 4 5 6 7 8
  * tile               (tile) int32 4B 1
  * layer              (layer) float64 160B 0.05 0.15 0.25 ... 18.9 41.4 58.9
  * lat                (lat) float64 8B 45.3
  * lon                (lon) float64 8B 5.77
Data variables: (12/104)
    ALBS               (tile, lat, lon) float64 8B 0.7283
    ALIC               (tile, icp1, lat, lon) float64 48B 0.0 0.0 ... 0.0 0.0
    ALVC               (tile, icp1, lat, lon) float64 48B 0.0 0.0 ... 0.0 0.0
    CLAY               (tile, layer, lat, lon) float64 160B 25.84 27.21 ... 0.0
    CMAS               (tile, ic, lat, lon) float64 40B 0.0 0.0 0.0 0.0 0.0
    Cmossmas           (tile, lat, lon) float64 8B 0.0
    ...                 ...
    imoss              (tile, lat, lon) float64 8B 0.0
    upMossSoilC        (tile, layer, lat, lon) float64 160B 0.0 0.0 ... 0.0 0.0
    Nmossmas           (tile, lat, lon) float64 8B 0.0
    litrmsmossN        (tile, lat, lon) float64 8B 0.0
    upMossSoilN        (tile, lat, lon) float64 8B 0.0
    bnf_moss           (tile, lat, lon) float64 8B 0.0
Attributes:
    title:          CLASSIC initialization file
    creation_date:  20241115
    history:        Wed Jun 12 17:19:00 2019: ncks -4 ./rsfile.nc ./rsfile.nc
    NCO:            4.4.2
    row_bounds:     1 1

In [4]:
ds.soilcmas 

<xarray.DataArray 'soilcmas' (tile: 1, layer: 20, iccp2: 14, lat: 1, lon: 1)> Size: 2kB
array([[[[[0.00000000e+00]],

         [[0.00000000e+00]],

         [[1.81632604e+00]],

         [[0.00000000e+00]],

         [[0.00000000e+00]],

         [[0.00000000e+00]],

         [[0.00000000e+00]],

         [[1.88599685e+01]],

         [[3.58983830e+01]],

         [[0.00000000e+00]],

...

         [[0.00000000e+00]],

         [[0.00000000e+00]],

         [[0.00000000e+00]],

         [[0.00000000e+00]],

         [[0.00000000e+00]],

         [[0.00000000e+00]],

         [[0.00000000e+00]],

         [[0.00000000e+00]],

         [[0.00000000e+00]],

         [[0.00000000e+00]]]]])
Coordinates:
  * iccp2    (iccp2) int32 56B 1 2 3 4 5 6 7 8 9 10 11 12 13 14
  * tile     (tile) int32 4B 1
  * layer    (layer) float64 160B 0.05 0.15 0.25 0.35 ... 8.9 18.9 41.4 58.9
  * lat      (lat) float64 8B 45.3
  * lon      (lon) float64 8B 5.77
Attributes:
    units:      kgC/m2
    long_name:  Soil C mass per soil layer

In [5]:
ds.soilcmas.sum()

<xarray.DataArray 'soilcmas' ()> Size: 8B
array(91.96156288)

In [6]:
total = []
for i, fcancmx in enumerate(ds.fcancmx.squeeze().values):
    total.append(fcancmx*ds.soilcmas[0, :, i, 0, 0].sum())

np.sum(total)

35.14121283316312

### Set STD

In [7]:
ds.stddevTopography

<xarray.DataArray 'stddevTopography' (tile: 1, lat: 1, lon: 1)> Size: 8B
array([[[0.]]])
Coordinates:
  * tile     (tile) int32 4B 1
  * lat      (lat) float64 8B 45.3
  * lon      (lon) float64 8B 5.77
Attributes:
    long_name:  Standard deviation of elevation
    units:      m

In [8]:
with xr.set_options(keep_attrs=True):
    ds['stddevTopography'][0, 0, 0] = 1000
ds.stddevTopography

<xarray.DataArray 'stddevTopography' (tile: 1, lat: 1, lon: 1)> Size: 8B
array([[[1000.]]])
Coordinates:
  * tile     (tile) int32 4B 1
  * lat      (lat) float64 8B 45.3
  * lon      (lon) float64 8B 5.77
Attributes:
    long_name:  Standard deviation of elevation
    units:      m

In [9]:
ds

<xarray.Dataset> Size: 11kB
Dimensions:            (tile: 1, lat: 1, lon: 1, icp1: 6, layer: 20, ic: 5,
                        icc: 12, iccp1: 13, iccp2: 14, slope: 8)
Coordinates:
  * ic                 (ic) int32 20B 1 2 3 4 5
  * icc                (icc) int32 48B 1 2 3 4 5 6 7 8 9 10 11 12
  * iccp1              (iccp1) int32 52B 1 2 3 4 5 6 7 8 9 10 11 12 13
  * iccp2              (iccp2) int32 56B 1 2 3 4 5 6 7 8 9 10 11 12 13 14
  * icp1               (icp1) int32 24B 1 2 3 4 5 6
  * slope              (slope) int32 32B 1 2 3 4 5 6 7 8
  * tile               (tile) int32 4B 1
  * layer              (layer) float64 160B 0.05 0.15 0.25 ... 18.9 41.4 58.9
  * lat                (lat) float64 8B 45.3
  * lon                (lon) float64 8B 5.77
Data variables: (12/104)
    ALBS               (tile, lat, lon) float64 8B 0.7283
    ALIC               (tile, icp1, lat, lon) float64 48B 0.0 0.0 ... 0.0 0.0
    ALVC               (tile, icp1, lat, lon) float64 48B 0.0 0.0 ... 0.0 0.0
    CLAY               (tile, layer, lat, lon) float64 160B 25.84 27.21 ... 0.0
    CMAS               (tile, ic, lat, lon) float64 40B 0.0 0.0 0.0 0.0 0.0
    Cmossmas           (tile, lat, lon) float64 8B 0.0
    ...                 ...
    imoss              (tile, lat, lon) float64 8B 0.0
    upMossSoilC        (tile, layer, lat, lon) float64 160B 0.0 0.0 ... 0.0 0.0
    Nmossmas           (tile, lat, lon) float64 8B 0.0
    litrmsmossN        (tile, lat, lon) float64 8B 0.0
    upMossSoilN        (tile, lat, lon) float64 8B 0.0
    bnf_moss           (tile, lat, lon) float64 8B 0.0
Attributes:
    title:          CLASSIC initialization file
    creation_date:  20241115
    history:        Wed Jun 12 17:19:00 2019: ncks -4 ./rsfile.nc ./rsfile.nc
    NCO:            4.4.2
    row_bounds:     1 1

## Save to netCDF
If CLASS would be run without CTEM further variables should be set. See: https://cccma.gitlab.io/classic/basicInputs.html -> Required vegetation data


In [10]:
path_out

'/home/lalandmi/eccc/SnowC2-CLASSIC-2D-model-private/inputFiles/SnowMIP/cdp'

In [11]:
exp

'STD_1000'

In [12]:
ds.to_netcdf(path_out+'/'+site+'_init_run_'+exp+'.nc')
ds.to_netcdf(path_out+'/rsfile_run_'+exp+'.nc')

In [13]:
!mkdir -p /home/lalandmi/eccc/SnowC2-CLASSIC-2D-model-private/outputFiles/SnowMIP/{site}/run_{exp}