# Set initialization file
https://cccma.gitlab.io/classic/makeInputFiles.html

Initialize the model for CLASSIC (CLASS+CTEM) run. Use the Paul's SnowMIP data to set the first soil layers proporties
and extend it.

In [1]:
# Env: sc2_v0

import xarray as xr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import proplot as pplt # New plot library (https://proplot.readthedocs.io/en/latest/)
pplt.rc['savefig.dpi'] = 300 # 1200 is too big! #https://proplot.readthedocs.io/en/latest/basics.html#Creating-figures

In [2]:
exp = 'Ref'
site = 'cdp_30_60_min'
site_paul = 'Col_de_Port'
site_ex = 'CA-Oas'
# site_ex = 'AU-Tum'

path_in = '/home/lalandmi/eccc/classic-develop/inputFiles/FLUXNETsites/'+site_ex # example file
path_out = '/home/lalandmi/eccc/classic-develop/inputFiles/SnowMIP/'+site

In [3]:
ds = xr.open_dataset(path_in+'/'+site_ex+'_init.nc')
ds.load()

<xarray.Dataset> Size: 11kB
Dimensions:            (tile: 1, lat: 1, lon: 1, icp1: 6, layer: 20, ic: 5,
                        icc: 12, iccp1: 13, iccp2: 14, slope: 8)
Coordinates:
  * ic                 (ic) int32 20B 1 2 3 4 5
  * icc                (icc) int32 48B 1 2 3 4 5 6 7 8 9 10 11 12
  * iccp1              (iccp1) int32 52B 1 2 3 4 5 6 7 8 9 10 11 12 13
  * iccp2              (iccp2) int32 56B 1 2 3 4 5 6 7 8 9 10 11 12 13 14
  * icp1               (icp1) int32 24B 1 2 3 4 5 6
  * lat                (lat) float64 8B 53.63
  * layer              (layer) int32 80B 1 2 3 4 5 6 7 ... 14 15 16 17 18 19 20
  * lon                (lon) float64 8B -106.2
  * slope              (slope) int32 32B 1 2 3 4 5 6 7 8
  * tile               (tile) int32 4B 1
Data variables: (12/101)
    ALBS               (tile, lat, lon) float64 8B 0.7647
    ALIC               (tile, icp1, lat, lon) float64 48B 0.0 0.29 ... 0.0 0.0
    ALVC               (tile, icp1, lat, lon) float64 48B 0.0 0.05 ... 0.0 0.0
    CLAY               (tile, layer, lat, lon) float64 160B 15.16 ... 23.29
    CMAS               (tile, ic, lat, lon) float64 40B 0.0 20.0 0.0 0.0 0.0
    Cmossmas           (tile, lat, lon) float64 8B 0.0
    ...                 ...
    stemmass_s         (tile, icc, lat, lon) float64 96B 0.0 0.0 0.0 ... 0.0 0.0
    stmhrlos           (tile, icc, lat, lon) float64 96B 0.0 0.0 0.0 ... 0.0 0.0
    tcoldm             (lat, lon) float32 4B 99.0
    twarmm             (lat, lon) float32 4B -99.0
    tymaxlai           (tile, icc, lat, lon) float64 96B 0.0 0.0 0.0 ... 0.0 0.0
    nh4_mass           (tile, iccp1, lat, lon) float32 52B 0.0 0.0 ... 0.0 0.0
Attributes:
    title:          CLASSIC initialization file created from: /home/acrp001/m...
    creation_date:  20190523
    history:        Wed Jun 12 17:19:01 2019: ncks -4 ./rsfile.nc ./rsfile.nc
    NCO:            4.4.2
    row_bounds:     1 1

In [4]:
ds.soilcmas.sum()

<xarray.DataArray 'soilcmas' ()> Size: 8B
array(0.)

## Col de Porte, France

Grassy meadow bordered by coniferous forest. Soils are 30% clay, 60% sand and 10% silt.

| Short name | cdp |
|:-----------|:----|
| Location | 45.30ºN, 5.77ºE |
| Elevation | 1325 m |
| Snow-free albedo | 0.2 |
| Simulation period | 1 October 1994 to 30 September 2014 |
| Temperature/humidity measurement height | 1.5 m |
| Wind measurement height | 10 m |
| Reference | Morin et al. (2012) |

In [5]:
lat = 45.30
lon = 5.77

# If the site description is not enough we can get the input data from gridded satellite datasets
path = '/home/lalandmi/Dropbox/data/CLASSIC/'
SoilGrids250m_CLAY = xr.open_dataset(path+'/soil/SoilGrids250m_CLAY_0.05deg.nc')
SoilGrids250m_ORGM = xr.open_dataset(path+'/soil/SoilGrids250m_ORGM_0.05deg.nc')
SoilGrids250m_SAND = xr.open_dataset(path+'/soil/SoilGrids250m_SAND_0.05deg.nc')
SoilGrids250m_SDEP = xr.open_dataset(path+'/soil/SoilGrids250m_SDEP_0.05deg.nc')
NCAR_SOCI = xr.open_dataset(path+'/soil/NCAR_SOCI_0.5deg.nc')
c4_fraction_1deg = xr.open_dataarray(path+'/vegetation/c4_fraction_1deg.nc')

path_paul = '/home/lalandmi/Dropbox/data/SnowMIP/Paul' 
ds_init_Paul = xr.open_dataset(path_paul+'/'+site_paul+'_60_ESMSnowMIP.nc').load()
ds_init_Paul

<xarray.Dataset> Size: 860B
Dimensions:            (lon: 1, lat: 1, tile: 1, icp1: 5, layer: 3, ic: 4,
                        icctem: 9, iccp2: 11, slope: 8)
Coordinates:
  * lon                (lon) float64 8B 5.77
  * lat                (lat) float64 8B 45.3
  * tile               (tile) int32 4B 1
  * icp1               (icp1) int32 20B 1 2 3 4 5
  * layer              (layer) int32 12B 1 2 3
  * ic                 (ic) int32 16B 1 2 3 4
  * icctem             (icctem) int32 36B 1 2 3 4 5 6 7 8 9
  * iccp2              (iccp2) int32 44B 1 2 3 4 5 6 7 8 9 10 11
  * slope              (slope) int32 32B 1 2 3 4 5 6 7 8
Data variables: (12/43)
    GC                 (lat, lon) float64 8B -1.0
    nmtest             (lat, lon) float64 8B 1.0
    FCAN               (tile, icp1, lat, lon) float64 40B 0.0 0.0 0.0 1.0 0.0
    LNZ0               (tile, icp1, lat, lon) float64 40B 0.0 0.0 0.0 -4.605 0.0
    ALIC               (tile, icp1, lat, lon) float64 40B 0.0 0.0 0.0 0.34 0.0
    ALVC               (tile, icp1, lat, lon) float64 40B 0.0 0.0 0.0 0.06 0.0
    ...                 ...
    srplsmon           (lat, lon) float64 8B 8.198e-319
    defctmon           (lat, lon) float64 8B 7.996e-319
    anndefct           (lat, lon) float64 8B 9.321e-314
    annsrpls           (lat, lon) float64 8B 7.905e-323
    annpcp             (lat, lon) float64 8B 0.0
    dry_season_length  (lat, lon) float64 8B 0.0
Attributes:
    title:          CLASSIC initialization file created from: /home/lalandmi/...
    creation_date:  20240123

### Set the layer coords to the center soil layer

In [6]:
layer_c = []

for i in range(len(ds.DELZ)):
    if i == 0:
        layer_c.append(ds.DELZ.cumsum().values[i]/2)
    else:
        layer_c.append(ds.DELZ.cumsum().values[i-1] + ds.DELZ.values[i]/2)
        
with xr.set_options(keep_attrs=True):
    ds = ds.assign_coords(layer=ds.layer*0+layer_c)

ds.layer

<xarray.DataArray 'layer' (layer: 20)> Size: 160B
array([5.00e-02, 1.50e-01, 2.50e-01, 3.50e-01, 4.50e-01, 5.50e-01, 6.50e-01,
       7.50e-01, 8.50e-01, 9.50e-01, 1.10e+00, 1.35e+00, 1.70e+00, 2.15e+00,
       2.90e+00, 4.90e+00, 8.90e+00, 1.89e+01, 4.14e+01, 5.89e+01])
Coordinates:
  * layer    (layer) float64 160B 0.05 0.15 0.25 0.35 ... 8.9 18.9 41.4 58.9
Attributes:
    standard_name:  ground layers

In [7]:
ds.DELZ.cumsum()

<xarray.DataArray 'DELZ' (layer: 20)> Size: 160B
array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.2,
        1.5,  1.9,  2.4,  3.4,  6.4, 11.4, 26.4, 56.4, 61.4])
Coordinates:
  * layer    (layer) float64 160B 0.05 0.15 0.25 0.35 ... 8.9 18.9 41.4 58.9

In [8]:
layer_c = []

for i in range(len(ds_init_Paul.DELZ)):
    if i == 0:
        layer_c.append(ds_init_Paul.DELZ.cumsum().values[i]/2)
    else:
        layer_c.append(ds_init_Paul.DELZ.cumsum().values[i-1] + ds_init_Paul.DELZ.values[i]/2)
        
with xr.set_options(keep_attrs=True):
    ds_init_Paul = ds_init_Paul.assign_coords(layer=ds_init_Paul.layer*0+layer_c)

ds_init_Paul.layer

<xarray.DataArray 'layer' (layer: 3)> Size: 24B
array([0.05 , 0.225, 2.225])
Coordinates:
  * layer    (layer) float64 24B 0.05 0.225 2.225
Attributes:
    standard_name:  ground layers

In [9]:
ds_init_Paul.DELZ.cumsum()

<xarray.DataArray 'DELZ' (layer: 3)> Size: 24B
array([0.1 , 0.35, 4.1 ])
Coordinates:
  * layer    (layer) float64 24B 0.05 0.225 2.225

### Use updated Lejeune et al. (2019) soil properties
See: https://github.com/mickaellalande/SnowC2/blob/main/CLASSIC/in_situ/SnowMIP/FR-Cdp_test/init/soil_properties_Lejeune2019.ipynb

The soil properties does not have much influence on the snowpack (https://github.com/mickaellalande/SnowC2/blob/main/CLASSIC/in_situ/SnowMIP/FR-Cdp_test/outputs/run_LJ19.ipynb)

#### SAND

In [10]:
ds_init_Paul.SAND.squeeze().values

array([60., 60., 60.])

In [15]:
SoilGrids250m_SAND.sel(lat=lat, lon=lon, method='nearest').SAND.values

array([32.395565, 36.187283, 37.77538 , 40.913506, 40.913506, 40.913506,
       43.26316 , 43.26316 , 43.26316 , 43.26316 , 44.67604 , 44.67604 ,
       44.67604 , 44.67604 , 44.67604 , 44.67604 , 44.67604 , 44.67604 ,
       44.67604 , 44.67604 ], dtype=float32)

In [11]:
SAND = [28.25548189, 28.80777238, 28.66299566, 29.99675194, 28.95281068,
        25.98472155, 28.65865952, 29.31868227, 24.48636717, 24.48636717,
        24.48636717, 24.48636717, 24.48636717, 24.48636717, 24.48636717,
        24.48636717, 24.48636717, 24.48636717, 24.48636717, 24.48636717] # Percentage of sand content (%)

#### CLAY

In [12]:
ds_init_Paul.CLAY.squeeze().values

array([30., 30., 30.])

In [13]:
SoilGrids250m_CLAY.sel(lat=lat, lon=lon, method='nearest').CLAY.values

array([15.919922, 17.875647, 18.736591, 19.944347, 19.944347, 19.944347,
       20.631968, 20.631968, 20.631968, 20.631968, 20.773958, 20.773958,
       20.773958, 20.773958, 20.773958, 20.773958, 20.773958, 20.773958,
       20.773958, 20.773958], dtype=float32)

In [14]:
CLAY = [25.84005334, 27.20888272, 32.57873729, 33.43587   , 31.91389359,
        32.80038622, 31.05888226, 29.72243531, 31.18883994, 31.18883994,
        31.18883994, 31.18883994, 31.18883994, 31.18883994, 31.18883994,
        31.18883994, 31.18883994, 31.18883994, 31.18883994, 31.18883994] # Percentage clay content (%)

#### ORGM

In [15]:
ds_init_Paul.ORGM.squeeze().values

array([0., 0., 0.])

In [16]:
SoilGrids250m_ORGM.sel(lat=lat, lon=lon, method='nearest').ORGM.values

array([21.54454  , 12.801723 ,  9.33908  ,  5.402299 ,  5.402299 ,
        5.402299 ,  4.0373564,  4.0373564,  4.0373564,  4.0373564,
        3.75     ,  3.75     ,  3.75     ,  3.75     ,  3.75     ,
        3.75     ,  3.75     ,  3.75     ,  3.75     ,  3.75     ],
      dtype=float32)

In [17]:
ORGM = [6.70155619, 4.30312283, 2.22649535, 0.8769751 , 0.52171461,
        0.40136692, 0.34275181, 0.34132661, 0.44593785, 0.44593785,
        0.44593785, 0.44593785, 0.44593785, 0.44593785, 0.44593785,
        0.44593785, 0.44593785, 0.44593785, 0.44593785, 0.44593785] # Percentage organic matter content (%)

In [18]:
ds_init_Paul.FCAN.squeeze().values

array([0., 0., 0., 1., 0.])

In [19]:
# These values can be attributed with the global grid if not available
SDEP = SoilGrids250m_SDEP.sel(lat=lat, lon=lon, method='nearest').SDEP.values.item(0) # Soil permeable depth (m)
SOCI = NCAR_SOCI.sel(lat=lat, lon=lon, method='nearest').SOCI.values.item(0) # Soil color inde
c4_fraction = c4_fraction_1deg.sel(lat=lat, lon=lon, method='nearest').values.item(0) # If grass

# ! List of CLASS-level PFTs
classpfts = ['NdlTr', 'BdlTr', 'Crops', 'Grass', 'BdlSh']
FCAN = {'NdlTr': 0. , 'BdlTr': 0., 'Crops': 0., 'Grass': 1., 'BdlSh': 0.} # max 1
# Maybe add a little fraction of trees (as it's bordered by coniferous -> TODO)

# ! List of CTEM PFTs
# ! **Note: 'BdlDCoTr' should be specified before 'BdlDDrTr' due to some code in competition.
ctempfts = ['NdlEvgTr', 'NdlDcdTr', 'BdlEvgTr', 'BdlDCoTr', 'BdlDDrTr', 'CropC3', 'CropC4', 'GrassC3', 'GrassC4', 'Sedge', 'BdlEvgSh', 'BdlDCoSh']
fcancmx = {'NdlEvgTr': 0., 'NdlDcdTr': 0., 'BdlEvgTr': 0., 'BdlDCoTr': 0., 'BdlDDrTr': 0., 'CropC3': 0., 'CropC4': 0., 
           'GrassC3': (1-c4_fraction), 'GrassC4': c4_fraction, 'Sedge': 0., 'BdlEvgSh': 0., 'BdlDCoSh': 0.} # Max 1
# Check differences between C3 and C4 at Cdp? (TODO)

if sum(FCAN.values()) > 1: raise Exception("The sum of FCAN values needs to be lower than 1.")
if sum(fcancmx.values()) > 1: raise Exception("The sum of fcanmax values needs to be lower than 1.")

print('SDEP = ' + str(SDEP))
print('\nSOCI = ' + str(SOCI))
print('\nCLAY = ' + str(CLAY))
print('\nSAND = ' + str(SAND))
print('\nORGM = ' + str(ORGM))
print('\nGrass C4 fraction = ' + str(c4_fraction))

SDEP = 13.369999885559082

SOCI = 15.0

CLAY = [25.84005334, 27.20888272, 32.57873729, 33.43587, 31.91389359, 32.80038622, 31.05888226, 29.72243531, 31.18883994, 31.18883994, 31.18883994, 31.18883994, 31.18883994, 31.18883994, 31.18883994, 31.18883994, 31.18883994, 31.18883994, 31.18883994, 31.18883994]

SAND = [28.25548189, 28.80777238, 28.66299566, 29.99675194, 28.95281068, 25.98472155, 28.65865952, 29.31868227, 24.48636717, 24.48636717, 24.48636717, 24.48636717, 24.48636717, 24.48636717, 24.48636717, 24.48636717, 24.48636717, 24.48636717, 24.48636717, 24.48636717]

ORGM = [6.70155619, 4.30312283, 2.22649535, 0.8769751, 0.52171461, 0.40136692, 0.34275181, 0.34132661, 0.44593785, 0.44593785, 0.44593785, 0.44593785, 0.44593785, 0.44593785, 0.44593785, 0.44593785, 0.44593785, 0.44593785, 0.44593785, 0.44593785]

Grass C4 fraction = 0.015699999406933784


### Set lat/lon

In [20]:
with xr.set_options(keep_attrs=True):
    ds = ds.assign_coords(lat=(ds.lat*0+lat))
    ds = ds.assign_coords(lon=(ds.lon*0+lon))
ds

<xarray.Dataset> Size: 11kB
Dimensions:            (tile: 1, lat: 1, lon: 1, icp1: 6, layer: 20, ic: 5,
                        icc: 12, iccp1: 13, iccp2: 14, slope: 8)
Coordinates:
  * ic                 (ic) int32 20B 1 2 3 4 5
  * icc                (icc) int32 48B 1 2 3 4 5 6 7 8 9 10 11 12
  * iccp1              (iccp1) int32 52B 1 2 3 4 5 6 7 8 9 10 11 12 13
  * iccp2              (iccp2) int32 56B 1 2 3 4 5 6 7 8 9 10 11 12 13 14
  * icp1               (icp1) int32 24B 1 2 3 4 5 6
  * slope              (slope) int32 32B 1 2 3 4 5 6 7 8
  * tile               (tile) int32 4B 1
  * layer              (layer) float64 160B 0.05 0.15 0.25 ... 18.9 41.4 58.9
  * lat                (lat) float64 8B 45.3
  * lon                (lon) float64 8B 5.77
Data variables: (12/101)
    ALBS               (tile, lat, lon) float64 8B 0.7647
    ALIC               (tile, icp1, lat, lon) float64 48B 0.0 0.29 ... 0.0 0.0
    ALVC               (tile, icp1, lat, lon) float64 48B 0.0 0.05 ... 0.0 0.0
    CLAY               (tile, layer, lat, lon) float64 160B 15.16 ... 23.29
    CMAS               (tile, ic, lat, lon) float64 40B 0.0 20.0 0.0 0.0 0.0
    Cmossmas           (tile, lat, lon) float64 8B 0.0
    ...                 ...
    stemmass_s         (tile, icc, lat, lon) float64 96B 0.0 0.0 0.0 ... 0.0 0.0
    stmhrlos           (tile, icc, lat, lon) float64 96B 0.0 0.0 0.0 ... 0.0 0.0
    tcoldm             (lat, lon) float32 4B 99.0
    twarmm             (lat, lon) float32 4B -99.0
    tymaxlai           (tile, icc, lat, lon) float64 96B 0.0 0.0 0.0 ... 0.0 0.0
    nh4_mass           (tile, iccp1, lat, lon) float32 52B 0.0 0.0 ... 0.0 0.0
Attributes:
    title:          CLASSIC initialization file created from: /home/acrp001/m...
    creation_date:  20190523
    history:        Wed Jun 12 17:19:01 2019: ncks -4 ./rsfile.nc ./rsfile.nc
    NCO:            4.4.2
    row_bounds:     1 1

### Set PFTs

In [21]:
for i, pft in enumerate(classpfts):
    ds.FCAN[0, i, 0, 0] = FCAN[pft]
    print(pft + ' -> ' + str(FCAN[pft]*100) + ' %')
    
ds.FCAN[0, :, 0, 0]
# 6th PFT: Bareground (need to be specified if CLASS used without CTEM)

NdlTr -> 0.0 %
BdlTr -> 0.0 %
Crops -> 0.0 %
Grass -> 100.0 %
BdlSh -> 0.0 %


<xarray.DataArray 'FCAN' (icp1: 6)> Size: 48B
array([0., 0., 0., 1., 0., 0.])
Coordinates:
  * icp1     (icp1) int32 24B 1 2 3 4 5 6
    tile     int32 4B 1
    lat      float64 8B 45.3
    lon      float64 8B 5.77
Attributes:
    units:      -
    long_name:  Annual maximum fractional coverage of modelled area (read in ...

In [22]:
for i, pft in enumerate(ctempfts):
    ds.fcancmx[0, i, 0, 0] = fcancmx[pft]
    print(pft + ' -> ' + str(fcancmx[pft]*100) + ' %')
    
ds.fcancmx[0, :, 0, 0]

NdlEvgTr -> 0.0 %
NdlDcdTr -> 0.0 %
BdlEvgTr -> 0.0 %
BdlDCoTr -> 0.0 %
BdlDDrTr -> 0.0 %
CropC3 -> 0.0 %
CropC4 -> 0.0 %
GrassC3 -> 98.43000005930662 %
GrassC4 -> 1.5699999406933784 %
Sedge -> 0.0 %
BdlEvgSh -> 0.0 %
BdlDCoSh -> 0.0 %


<xarray.DataArray 'fcancmx' (icc: 12)> Size: 96B
array([0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.9843,
       0.0157, 0.    , 0.    , 0.    ])
Coordinates:
  * icc      (icc) int32 48B 1 2 3 4 5 6 7 8 9 10 11 12
    tile     int32 4B 1
    lat      float64 8B 45.3
    lon      float64 8B 5.77
Attributes:
    units:      -
    long_name:  PFT fractional coverage per grid cell

### Set soil color

In [23]:
with xr.set_options(keep_attrs=True):
    ds['SOCI'][0, 0, 0] = SOCI
ds.SOCI

<xarray.DataArray 'SOCI' (tile: 1, lat: 1, lon: 1)> Size: 8B
array([[[15.]]])
Coordinates:
  * tile     (tile) int32 4B 1
  * lat      (lat) float64 8B 45.3
  * lon      (lon) float64 8B 5.77
Attributes:
    units:      index
    long_name:  Soil colour index

### Set permeable depth

In [24]:
with xr.set_options(keep_attrs=True):
    ds['SDEP'][0, 0, 0] = SDEP
ds.SDEP

<xarray.DataArray 'SDEP' (tile: 1, lat: 1, lon: 1)> Size: 8B
array([[[13.36999989]]])
Coordinates:
  * tile     (tile) int32 4B 1
  * lat      (lat) float64 8B 45.3
  * lon      (lon) float64 8B 5.77
Attributes:
    units:      m
    long_name:  Soil permeable depth

### Check maximum level before bedrock
https://gitlab.com/jormelton/classic/-/blob/develop/src/modelStateDrivers.f90?ref_type=heads#L968

In [25]:
ds.DELZ

<xarray.DataArray 'DELZ' (layer: 20)> Size: 160B
array([ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.2,
        0.3,  0.4,  0.5,  1. ,  3. ,  5. , 15. , 30. ,  5. ])
Coordinates:
  * layer    (layer) float64 160B 0.05 0.15 0.25 0.35 ... 8.9 18.9 41.4 58.9
Attributes:
    units:      m
    long_name:  Ground layer thickness

In [26]:
i = 0
while ds.DELZ.cumsum()[i] < SDEP:
    i += 1
    if i > ds.DELZ.shape[0]-1:
        print('The permable depth is greater than the model levels')
        break
        
maxlevel = i + 1 # first level of bedrock (next to the one containing SDEP)
maxlevel

18

In [27]:
ds.DELZ.cumsum()

<xarray.DataArray 'DELZ' (layer: 20)> Size: 160B
array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.2,
        1.5,  1.9,  2.4,  3.4,  6.4, 11.4, 26.4, 56.4, 61.4])
Coordinates:
  * layer    (layer) float64 160B 0.05 0.15 0.25 0.35 ... 8.9 18.9 41.4 58.9

In [28]:
ds.DELZ.cumsum()[maxlevel]

<xarray.DataArray 'DELZ' ()> Size: 8B
array(56.4)
Coordinates:
    layer    float64 8B 41.4

In [29]:
ds.DELZ.cumsum()[:maxlevel]

<xarray.DataArray 'DELZ' (layer: 18)> Size: 144B
array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.2,
        1.5,  1.9,  2.4,  3.4,  6.4, 11.4, 26.4])
Coordinates:
  * layer    (layer) float64 144B 0.05 0.15 0.25 0.35 0.45 ... 2.9 4.9 8.9 18.9

In [30]:
ds.DELZ.cumsum()[maxlevel:]

<xarray.DataArray 'DELZ' (layer: 2)> Size: 16B
array([56.4, 61.4])
Coordinates:
  * layer    (layer) float64 16B 41.4 58.9

### Set soil contents and flags
Note: flags are only set in the SAND variable (-3 bedrock / -2 peatland)

In [31]:
with xr.set_options(keep_attrs=True):
    # Set values until bedrock
    ds.SAND[0, :maxlevel, 0, 0] = SAND[:maxlevel]
    ds.CLAY[0, :maxlevel, 0, 0] = CLAY[:maxlevel]
    ds.ORGM[0, :maxlevel, 0, 0] = ORGM[:maxlevel]
    
    # Set bedrock values
    ds.SAND[0, maxlevel:, 0, 0] = -3 # flag for bedrock
    ds.CLAY[0, maxlevel:, 0, 0] = 0.
    ds.ORGM[0, maxlevel:, 0, 0] = 0.

In [32]:
# Current values
ds.SAND[0, :, 0, 0]

<xarray.DataArray 'SAND' (layer: 20)> Size: 160B
array([28.25548189, 28.80777238, 28.66299566, 29.99675194, 28.95281068,
       25.98472155, 28.65865952, 29.31868227, 24.48636717, 24.48636717,
       24.48636717, 24.48636717, 24.48636717, 24.48636717, 24.48636717,
       24.48636717, 24.48636717, 24.48636717, -3.        , -3.        ])
Coordinates:
    tile     int32 4B 1
  * layer    (layer) float64 160B 0.05 0.15 0.25 0.35 ... 8.9 18.9 41.4 58.9
    lat      float64 8B 45.3
    lon      float64 8B 5.77
Attributes:
    units:      %
    long_name:  Percentage sand content

In [33]:
ds.CLAY[0, :, 0, 0]

<xarray.DataArray 'CLAY' (layer: 20)> Size: 160B
array([25.84005334, 27.20888272, 32.57873729, 33.43587   , 31.91389359,
       32.80038622, 31.05888226, 29.72243531, 31.18883994, 31.18883994,
       31.18883994, 31.18883994, 31.18883994, 31.18883994, 31.18883994,
       31.18883994, 31.18883994, 31.18883994,  0.        ,  0.        ])
Coordinates:
    tile     int32 4B 1
  * layer    (layer) float64 160B 0.05 0.15 0.25 0.35 ... 8.9 18.9 41.4 58.9
    lat      float64 8B 45.3
    lon      float64 8B 5.77
Attributes:
    units:      %
    long_name:  Percentage clay content

In [34]:
ds.ORGM[0, :, 0, 0]

<xarray.DataArray 'ORGM' (layer: 20)> Size: 160B
array([6.70155619, 4.30312283, 2.22649535, 0.8769751 , 0.52171461,
       0.40136692, 0.34275181, 0.34132661, 0.44593785, 0.44593785,
       0.44593785, 0.44593785, 0.44593785, 0.44593785, 0.44593785,
       0.44593785, 0.44593785, 0.44593785, 0.        , 0.        ])
Coordinates:
    tile     int32 4B 1
  * layer    (layer) float64 160B 0.05 0.15 0.25 0.35 ... 8.9 18.9 41.4 58.9
    lat      float64 8B 45.3
    lon      float64 8B 5.77
Attributes:
    units:      %
    long_name:  Percentage organic matter content

In [35]:
ds

<xarray.Dataset> Size: 11kB
Dimensions:            (tile: 1, lat: 1, lon: 1, icp1: 6, layer: 20, ic: 5,
                        icc: 12, iccp1: 13, iccp2: 14, slope: 8)
Coordinates:
  * ic                 (ic) int32 20B 1 2 3 4 5
  * icc                (icc) int32 48B 1 2 3 4 5 6 7 8 9 10 11 12
  * iccp1              (iccp1) int32 52B 1 2 3 4 5 6 7 8 9 10 11 12 13
  * iccp2              (iccp2) int32 56B 1 2 3 4 5 6 7 8 9 10 11 12 13 14
  * icp1               (icp1) int32 24B 1 2 3 4 5 6
  * slope              (slope) int32 32B 1 2 3 4 5 6 7 8
  * tile               (tile) int32 4B 1
  * layer              (layer) float64 160B 0.05 0.15 0.25 ... 18.9 41.4 58.9
  * lat                (lat) float64 8B 45.3
  * lon                (lon) float64 8B 5.77
Data variables: (12/101)
    ALBS               (tile, lat, lon) float64 8B 0.7647
    ALIC               (tile, icp1, lat, lon) float64 48B 0.0 0.29 ... 0.0 0.0
    ALVC               (tile, icp1, lat, lon) float64 48B 0.0 0.05 ... 0.0 0.0
    CLAY               (tile, layer, lat, lon) float64 160B 25.84 27.21 ... 0.0
    CMAS               (tile, ic, lat, lon) float64 40B 0.0 20.0 0.0 0.0 0.0
    Cmossmas           (tile, lat, lon) float64 8B 0.0
    ...                 ...
    stemmass_s         (tile, icc, lat, lon) float64 96B 0.0 0.0 0.0 ... 0.0 0.0
    stmhrlos           (tile, icc, lat, lon) float64 96B 0.0 0.0 0.0 ... 0.0 0.0
    tcoldm             (lat, lon) float32 4B 99.0
    twarmm             (lat, lon) float32 4B -99.0
    tymaxlai           (tile, icc, lat, lon) float64 96B 0.0 0.0 0.0 ... 0.0 0.0
    nh4_mass           (tile, iccp1, lat, lon) float32 52B 0.0 0.0 ... 0.0 0.0
Attributes:
    title:          CLASSIC initialization file created from: /home/acrp001/m...
    creation_date:  20190523
    history:        Wed Jun 12 17:19:01 2019: ncks -4 ./rsfile.nc ./rsfile.nc
    NCO:            4.4.2
    row_bounds:     1 1

## Save to netCDF
If CLASS would be run without CTEM further variables should be set. See: https://cccma.gitlab.io/classic/basicInputs.html -> Required vegetation data


In [38]:
exp

'Ref'

In [36]:
ds.to_netcdf(path_out+'/'+site+'_init_spinup_'+exp+'.nc')
ds.to_netcdf(path_out+'/rsfile_spinup_'+exp+'.nc')

In [37]:
!mkdir -p /home/lalandmi/eccc/classic-develop/outputFiles/SnowMIP/{site}/spinup_{exp}

In [39]:
exp2 = 'Ref_30min'

In [40]:
ds.to_netcdf(path_out+'/'+site+'_init_spinup_'+exp2+'.nc')
ds.to_netcdf(path_out+'/rsfile_spinup_'+exp2+'.nc')

In [41]:
!mkdir -p /home/lalandmi/eccc/classic-develop/outputFiles/SnowMIP/{site}/spinup_{exp2}