In [1]:
# To reload external files automatically (ex: utils)
%load_ext autoreload
%autoreload 2

import xarray as xr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import proplot as plot # New plot library (https://proplot.readthedocs.io/en/latest/)
plot.rc['savefig.dpi'] = 300 # 1200 is too big! #https://proplot.readthedocs.io/en/latest/basics.html#Creating-figures
from scipy import stats
import xesmf as xe # For regridding (https://xesmf.readthedocs.io/en/latest/)
import calendar

In [2]:
path = '/home/lalandmi/eccc/CLASSIC/inputFiles/test/AU-Tum'

In [32]:
ds = xr.open_dataset(path+'/AU-Tum_init.nc')
ds

<xarray.Dataset>
Dimensions:          (ic: 4, iccp2: 11, icctem: 9, icp1: 5, lat: 1, layer: 20, lon: 1, slope: 8, tile: 1)
Coordinates:
  * ic               (ic) int32 1 2 3 4
  * iccp2            (iccp2) int32 1 2 3 4 5 6 7 8 9 10 11
  * icctem           (icctem) int32 1 2 3 4 5 6 7 8 9
  * icp1             (icp1) int32 1 2 3 4 5
  * lat              (lat) float64 -35.66
  * layer            (layer) int32 1 2 3 4 5 6 7 8 9 ... 13 14 15 16 17 18 19 20
  * lon              (lon) float64 148.2
  * slope            (slope) int32 1 2 3 4 5 6 7 8
  * tile             (tile) int32 1
Data variables:
    ALBS             (tile, lat, lon) float64 ...
    ALIC             (tile, icp1, lat, lon) float64 ...
    ALVC             (tile, icp1, lat, lon) float64 ...
    CLAY             (tile, layer, lat, lon) float64 ...
    CMAS             (tile, ic, lat, lon) float64 ...
    Cmossmas         (tile, lat, lon) float64 ...
    DELZ             (layer) float64 ...
    DRN              (tile, lat, lon) float64 ...
    FARE             (tile, lat, lon) float64 ...
    FCAN             (tile, icp1, lat, lon) float64 ...
    GC               (lat, lon) float64 ...
    GRO              (tile, lat, lon) float64 ...
    LNZ0             (tile, icp1, lat, lon) float64 ...
    MID              (lat, lon) float64 ...
    ORGM             (tile, layer, lat, lon) float64 ...
    PAMN             (tile, ic, lat, lon) float64 ...
    PAMX             (tile, ic, lat, lon) float64 ...
    RCAN             (tile, lat, lon) float64 ...
    RHOS             (tile, lat, lon) float64 ...
    ROOT             (tile, ic, lat, lon) float64 ...
    SAND             (tile, layer, lat, lon) float64 ...
    SCAN             (tile, lat, lon) float64 ...
    SDEP             (tile, lat, lon) float64 ...
    SNO              (tile, lat, lon) float64 ...
    SOCI             (tile, lat, lon) float64 ...
    TBAR             (tile, layer, lat, lon) float64 ...
    TCAN             (tile, lat, lon) float64 ...
    THIC             (tile, layer, lat, lon) float64 ...
    THLQ             (tile, layer, lat, lon) float64 ...
    TPND             (tile, lat, lon) float64 ...
    TSNO             (tile, lat, lon) float64 ...
    ZPND             (tile, lat, lon) float64 ...
    bleafmas         (tile, icctem, lat, lon) float64 ...
    dmoss            (tile, lat, lon) float64 ...
    fcancmx          (tile, icctem, lat, lon) float64 ...
    gleafmas         (tile, icctem, lat, lon) float64 ...
    grclarea         (lat, lon) float64 ...
    ipeatland        (tile, lat, lon) float64 ...
    lfstatus         (tile, icctem, lat, lon) float64 ...
    litrmass         (tile, iccp2, lat, lon) float64 ...
    litrmsmoss       (tile, lat, lon) float64 ...
    nmtest           (lat, lon) float64 ...
    pandays          (tile, icctem, lat, lon) float64 ...
    rootmass         (tile, icctem, lat, lon) float64 ...
    slopefrac        (tile, slope, lat, lon) float64 ...
    soilcmas         (tile, iccp2, lat, lon) float64 ...
    stemmass         (tile, icctem, lat, lon) float64 ...
    maxAnnualActLyr  (tile, lat, lon) float64 ...
    grwtheff         (tile, icctem, lat, lon) float64 ...
Attributes:
    title:          CLASSIC initialization file created from: /home/acrp001/m...
    creation_date:  20190523
    history:        Wed Jun 12 17:19:00 2019: ncks -4 ./rsfile.nc ./rsfile.nc
    NCO:            4.4.2
    row_bounds:     1 1

## Set data for Col de Porte 

5.4 Col de Porte, France  
Grassy meadow bordered by coniferous forest. Soils are 30% clay, 60% sand and 10% silt.  
Table 5.4: Col de Porte site characteristics   
- Short name: cdp
- Location: 45.30ºN, 5.77ºE
- Elevation: 1325 m
- Snow-free albedo: 0.2
- Simulation period: 1 October 1994 to 30 September 2014
- Temperature/humidity measurement height: 1.5 m above the snow surface
- Wind measurement height: 10 m
- Reference: Morin et al. (2012)

### Set lat/lon

In [33]:
with xr.set_options(keep_attrs=True):
    ds = ds.assign_coords(lon=(ds.lon*0+5.77))
    ds = ds.assign_coords(lat=(ds.lat*0+45.30))

In [10]:
ds

<xarray.Dataset>
Dimensions:          (ic: 4, iccp2: 11, icctem: 9, icp1: 5, lat: 1, layer: 20, lon: 1, slope: 8, tile: 1)
Coordinates:
  * ic               (ic) int32 1 2 3 4
  * iccp2            (iccp2) int32 1 2 3 4 5 6 7 8 9 10 11
  * icctem           (icctem) int32 1 2 3 4 5 6 7 8 9
  * icp1             (icp1) int32 1 2 3 4 5
  * lat              (lat) float64 45.3
  * layer            (layer) int32 1 2 3 4 5 6 7 8 9 ... 13 14 15 16 17 18 19 20
  * lon              (lon) float64 5.77
  * slope            (slope) int32 1 2 3 4 5 6 7 8
  * tile             (tile) int32 1
Data variables:
    ALBS             (tile, lat, lon) float64 0.5643
    ALIC             (tile, icp1, lat, lon) float64 0.0 0.0 0.0 0.0 0.0
    ALVC             (tile, icp1, lat, lon) float64 0.0 0.0 0.0 0.0 0.0
    CLAY             (tile, layer, lat, lon) float64 19.0 21.4 23.8 ... 0.0 0.0
    CMAS             (tile, ic, lat, lon) float64 0.0 0.0 0.0 0.0
    Cmossmas         (tile, lat, lon) float64 0.0
    DELZ             (layer) float64 0.1 0.1 0.1 0.1 0.1 ... 5.0 15.0 30.0 5.0
    DRN              (tile, lat, lon) float64 0.1
    FARE             (tile, lat, lon) float64 1.0
    FCAN             (tile, icp1, lat, lon) float64 0.0 0.58 0.0 0.42 0.0
    GC               (lat, lon) float64 -1.0
    GRO              (tile, lat, lon) float64 0.4285
    LNZ0             (tile, icp1, lat, lon) float64 0.0 0.0 0.0 0.0 0.0
    MID              (lat, lon) float64 1.0
    ORGM             (tile, layer, lat, lon) float64 6.4 6.6 6.8 ... 0.0 0.0 0.0
    PAMN             (tile, ic, lat, lon) float64 0.0 0.0 0.0 0.0
    PAMX             (tile, ic, lat, lon) float64 0.0 0.0 0.0 0.0
    RCAN             (tile, lat, lon) float64 0.0
    RHOS             (tile, lat, lon) float64 0.0
    ROOT             (tile, ic, lat, lon) float64 0.0 0.0 0.0 0.0
    SAND             (tile, layer, lat, lon) float64 64.0 61.6 ... -3.0 -3.0
    SCAN             (tile, lat, lon) float64 0.0
    SDEP             (tile, lat, lon) float64 3.5
    SNO              (tile, lat, lon) float64 0.0
    SOCI             (tile, lat, lon) float64 19.0
    TBAR             (tile, layer, lat, lon) float64 22.7 26.21 ... 12.61 12.61
    TCAN             (tile, lat, lon) float64 11.54
    THIC             (tile, layer, lat, lon) float64 0.0 0.0 0.0 ... 0.0 0.0 0.0
    THLQ             (tile, layer, lat, lon) float64 0.1392 0.1897 ... 0.0 0.0
    TPND             (tile, lat, lon) float64 0.0
    TSNO             (tile, lat, lon) float64 -273.2
    ZPND             (tile, lat, lon) float64 0.0
    bleafmas         (tile, icctem, lat, lon) float64 0.0 0.0 ... 0.01204
    dmoss            (tile, lat, lon) float64 0.0
    fcancmx          (tile, icctem, lat, lon) float64 0.0 0.0 ... 0.2646 0.1554
    gleafmas         (tile, icctem, lat, lon) float64 0.03069 0.0 ... 0.1243
    grclarea         (lat, lon) float64 100.0
    ipeatland        (tile, lat, lon) float64 0.0
    lfstatus         (tile, icctem, lat, lon) float64 1.0 4.0 1.0 ... 1.0 1.0
    litrmass         (tile, iccp2, lat, lon) float64 0.09167 0.0 ... 0.0 0.0
    litrmsmoss       (tile, lat, lon) float64 0.0
    nmtest           (lat, lon) float64 1.0
    pandays          (tile, icctem, lat, lon) float64 0.0 0.0 7.0 ... 7.0 7.0
    rootmass         (tile, icctem, lat, lon) float64 0.07974 0.0 ... 2.125
    slopefrac        (tile, slope, lat, lon) float64 0.0 0.0 0.0 ... 0.0 0.0 0.0
    soilcmas         (tile, iccp2, lat, lon) float64 0.5101 0.0 ... 0.0 0.0
    stemmass         (tile, icctem, lat, lon) float64 0.1253 0.0 ... 0.0 0.0
    maxAnnualActLyr  (tile, lat, lon) float64 61.4
    grwtheff         (tile, icctem, lat, lon) float64 100.0 100.0 ... 0.0 49.6
Attributes:
    title:          CLASSIC initialization file created from: /home/acrp001/m...
    creation_date:  20190523
    history:        Wed Jun 12 17:19:00 2019: ncks -4 ./rsfile.nc ./rsfile.nc
    NCO:            4.4.2
    row_bounds:     1 1

In [14]:
ds.CLAY

<xarray.DataArray 'CLAY' (tile: 1, layer: 20, lat: 1, lon: 1)>
array([[[[19.  ]],

        [[21.4 ]],

        [[23.8 ]],

        [[25.16]],

        [[25.48]],

        [[25.8 ]],

        [[26.12]],

        [[26.44]],

        [[26.76]],

        [[27.08]],

        [[27.72]],

        [[28.68]],

        [[29.96]],

        [[31.56]],

        [[34.76]],

        [[ 0.  ]],

        [[ 0.  ]],

        [[ 0.  ]],

        [[ 0.  ]],

        [[ 0.  ]]]])
Coordinates:
  * lat      (lat) float64 45.3
  * layer    (layer) int32 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
  * lon      (lon) float64 5.77
  * tile     (tile) int32 1
Attributes:
    units:      %
    long_name:  Percentage clay content

In [34]:
with xr.set_options(keep_attrs=True):
    ds.CLAY[0, :-5, 0, 0] = 30
ds.CLAY

<xarray.DataArray 'CLAY' (tile: 1, layer: 20, lat: 1, lon: 1)>
array([[[[30.]],

        [[30.]],

        [[30.]],

        [[30.]],

        [[30.]],

        [[30.]],

        [[30.]],

        [[30.]],

        [[30.]],

        [[30.]],

        [[30.]],

        [[30.]],

        [[30.]],

        [[30.]],

        [[30.]],

        [[ 0.]],

        [[ 0.]],

        [[ 0.]],

        [[ 0.]],

        [[ 0.]]]])
Coordinates:
  * lat      (lat) float64 45.3
  * layer    (layer) int32 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
  * lon      (lon) float64 5.77
  * tile     (tile) int32 1
Attributes:
    units:      %
    long_name:  Percentage clay content

In [127]:
ds.SAND

<xarray.DataArray 'SAND' (tile: 1, layer: 20, lat: 1, lon: 1)>
array([[[[64.      ]],

        [[61.6     ]],

        [[59.2     ]],

        [[57.693333]],

        [[57.08    ]],

        [[56.466667]],

        [[55.853333]],

        [[55.24    ]],

        [[54.626667]],

        [[54.013333]],

        [[52.786667]],

        [[50.946667]],

        [[48.493333]],

        [[45.426667]],

        [[39.293333]],

        [[-3.      ]],

        [[-3.      ]],

        [[-3.      ]],

        [[-3.      ]],

        [[-3.      ]]]])
Coordinates:
  * lat      (lat) float64 45.3
  * layer    (layer) int32 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
  * lon      (lon) float64 5.77
  * tile     (tile) int32 1
Attributes:
    units:      %
    long_name:  Percentage sand content

In [35]:
with xr.set_options(keep_attrs=True):
    ds.SAND[0, :-5, 0, 0] = 60
ds.SAND

<xarray.DataArray 'SAND' (tile: 1, layer: 20, lat: 1, lon: 1)>
array([[[[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[-3.]],

        [[-3.]],

        [[-3.]],

        [[-3.]],

        [[-3.]]]])
Coordinates:
  * lat      (lat) float64 45.3
  * layer    (layer) int32 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
  * lon      (lon) float64 5.77
  * tile     (tile) int32 1
Attributes:
    units:      %
    long_name:  Percentage sand content

In [36]:
with xr.set_options(keep_attrs=True):
    ds.ORGM[0, :, 0, 0] = 0
ds.ORGM

<xarray.DataArray 'ORGM' (tile: 1, layer: 20, lat: 1, lon: 1)>
array([[[[0.]],

        [[0.]],

        [[0.]],

        [[0.]],

        [[0.]],

        [[0.]],

        [[0.]],

        [[0.]],

        [[0.]],

        [[0.]],

        [[0.]],

        [[0.]],

        [[0.]],

        [[0.]],

        [[0.]],

        [[0.]],

        [[0.]],

        [[0.]],

        [[0.]],

        [[0.]]]])
Coordinates:
  * lat      (lat) float64 45.3
  * layer    (layer) int32 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
  * lon      (lon) float64 5.77
  * tile     (tile) int32 1
Attributes:
    units:      %
    long_name:  Percentage organic matter content

In [130]:
ds

<xarray.Dataset>
Dimensions:          (ic: 4, iccp2: 11, icctem: 9, icp1: 5, lat: 1, layer: 20, lon: 1, slope: 8, tile: 1)
Coordinates:
  * ic               (ic) int32 1 2 3 4
  * iccp2            (iccp2) int32 1 2 3 4 5 6 7 8 9 10 11
  * icctem           (icctem) int32 1 2 3 4 5 6 7 8 9
  * icp1             (icp1) int32 1 2 3 4 5
  * lat              (lat) float64 45.3
  * layer            (layer) int32 1 2 3 4 5 6 7 8 9 ... 13 14 15 16 17 18 19 20
  * lon              (lon) float64 5.77
  * slope            (slope) int32 1 2 3 4 5 6 7 8
  * tile             (tile) int32 1
Data variables:
    ALBS             (tile, lat, lon) float64 0.5643
    ALIC             (tile, icp1, lat, lon) float64 0.0 0.0 0.0 0.0 0.0
    ALVC             (tile, icp1, lat, lon) float64 0.0 0.0 0.0 0.0 0.0
    CLAY             (tile, layer, lat, lon) float64 30.0 30.0 30.0 ... 0.0 0.0
    CMAS             (tile, ic, lat, lon) float64 0.0 0.0 0.0 0.0
    Cmossmas         (tile, lat, lon) float64 0.0
    DELZ             (layer) float64 0.1 0.1 0.1 0.1 0.1 ... 5.0 15.0 30.0 5.0
    DRN              (tile, lat, lon) float64 0.1
    FARE             (tile, lat, lon) float64 1.0
    FCAN             (tile, icp1, lat, lon) float64 0.0 0.58 0.0 0.42 0.0
    GC               (lat, lon) float64 -1.0
    GRO              (tile, lat, lon) float64 0.4285
    LNZ0             (tile, icp1, lat, lon) float64 0.0 0.0 0.0 0.0 0.0
    MID              (lat, lon) float64 1.0
    ORGM             (tile, layer, lat, lon) float64 0.0 0.0 0.0 ... 0.0 0.0 0.0
    PAMN             (tile, ic, lat, lon) float64 0.0 0.0 0.0 0.0
    PAMX             (tile, ic, lat, lon) float64 0.0 0.0 0.0 0.0
    RCAN             (tile, lat, lon) float64 0.0
    RHOS             (tile, lat, lon) float64 0.0
    ROOT             (tile, ic, lat, lon) float64 0.0 0.0 0.0 0.0
    SAND             (tile, layer, lat, lon) float64 60.0 60.0 ... -3.0 -3.0
    SCAN             (tile, lat, lon) float64 0.0
    SDEP             (tile, lat, lon) float64 3.5
    SNO              (tile, lat, lon) float64 0.0
    SOCI             (tile, lat, lon) float64 19.0
    TBAR             (tile, layer, lat, lon) float64 22.7 26.21 ... 12.61 12.61
    TCAN             (tile, lat, lon) float64 11.54
    THIC             (tile, layer, lat, lon) float64 0.0 0.0 0.0 ... 0.0 0.0 0.0
    THLQ             (tile, layer, lat, lon) float64 0.1392 0.1897 ... 0.0 0.0
    TPND             (tile, lat, lon) float64 0.0
    TSNO             (tile, lat, lon) float64 -273.2
    ZPND             (tile, lat, lon) float64 0.0
    bleafmas         (tile, icctem, lat, lon) float64 0.0 0.0 ... 0.01204
    dmoss            (tile, lat, lon) float64 0.0
    fcancmx          (tile, icctem, lat, lon) float64 0.0 0.0 ... 0.2646 0.1554
    gleafmas         (tile, icctem, lat, lon) float64 0.03069 0.0 ... 0.1243
    grclarea         (lat, lon) float64 100.0
    ipeatland        (tile, lat, lon) float64 0.0
    lfstatus         (tile, icctem, lat, lon) float64 1.0 4.0 1.0 ... 1.0 1.0
    litrmass         (tile, iccp2, lat, lon) float64 0.09167 0.0 ... 0.0 0.0
    litrmsmoss       (tile, lat, lon) float64 0.0
    nmtest           (lat, lon) float64 1.0
    pandays          (tile, icctem, lat, lon) float64 0.0 0.0 7.0 ... 7.0 7.0
    rootmass         (tile, icctem, lat, lon) float64 0.07974 0.0 ... 2.125
    slopefrac        (tile, slope, lat, lon) float64 0.0 0.0 0.0 ... 0.0 0.0 0.0
    soilcmas         (tile, iccp2, lat, lon) float64 0.5101 0.0 ... 0.0 0.0
    stemmass         (tile, icctem, lat, lon) float64 0.1253 0.0 ... 0.0 0.0
    maxAnnualActLyr  (tile, lat, lon) float64 61.4
    grwtheff         (tile, icctem, lat, lon) float64 100.0 100.0 ... 0.0 49.6
Attributes:
    title:          CLASSIC initialization file created from: /home/acrp001/m...
    creation_date:  20190523
    history:        Wed Jun 12 17:19:00 2019: ncks -4 ./rsfile.nc ./rsfile.nc
    NCO:            4.4.2
    row_bounds:     1 1

In [131]:
ds.SAND

<xarray.DataArray 'SAND' (tile: 1, layer: 20, lat: 1, lon: 1)>
array([[[[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[60.]],

        [[-3.]],

        [[-3.]],

        [[-3.]],

        [[-3.]],

        [[-3.]]]])
Coordinates:
  * lat      (lat) float64 45.3
  * layer    (layer) int32 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
  * lon      (lon) float64 5.77
  * tile     (tile) int32 1
Attributes:
    units:      %
    long_name:  Percentage sand content

In [132]:
ds.DELZ

<xarray.DataArray 'DELZ' (layer: 20)>
array([ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.2,  0.3,
        0.4,  0.5,  1. ,  3. ,  5. , 15. , 30. ,  5. ])
Coordinates:
  * layer    (layer) int32 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
Attributes:
    units:      m
    long_name:  Ground layer thickness

In [133]:
ds.DELZ[:-3]

<xarray.DataArray 'DELZ' (layer: 17)>
array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2, 0.3, 0.4, 0.5,
       1. , 3. , 5. ])
Coordinates:
  * layer    (layer) int32 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17
Attributes:
    units:      m
    long_name:  Ground layer thickness

In [104]:
ds.DELZ[:17]

<xarray.DataArray 'DELZ' (layer: 17)>
array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2, 0.3, 0.4, 0.5,
       1. , 3. , 5. ])
Coordinates:
  * layer    (layer) int32 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17
Attributes:
    units:      m
    long_name:  Ground layer thickness

In [100]:
ds.DELZ[:17].sum()

<xarray.DataArray 'DELZ' ()>
array(11.4)

In [87]:
ds.SAND[0, :, 0, 0]

<xarray.DataArray 'SAND' (layer: 20)>
array([60., 60., 60., 60., 60., 60., 60., 60., 60., 60., 60., 60., 60., 60.,
       60., -3., -3., -3., -3., -3.])
Coordinates:
    lat      float64 45.3
  * layer    (layer) int32 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
    lon      float64 5.77
    tile     int32 1
Attributes:
    units:      %
    long_name:  Percentage sand content

In [84]:
ds.DELZ.where(ds.SAND != -3).sum()

<xarray.DataArray 'DELZ' ()>
array(3.4)

In [79]:
ds.SDEP

<xarray.DataArray 'SDEP' (tile: 1, lat: 1, lon: 1)>
array([[[3.5]]])
Coordinates:
  * lat      (lat) float64 45.3
  * lon      (lon) float64 5.77
  * tile     (tile) int32 1
Attributes:
    units:      m
    long_name:  Soil permeable depth

In [113]:
with xr.set_options(keep_attrs=True):
    # ds['SDEP'] = 12.0
    ds['SDEP'] = 3.5
ds.SDEP

<xarray.DataArray 'SDEP' ()>
array(3.4)

### PFT

! modelpft assigns the PFTs to their position in the kk sized matrix for CLASS and CTEM:  
modelpft(1:3)  = 1,     1,     0,      ! CLASS PFT 1 NDL (NdlTr)  
!               EVG    DCD  
modelpft(4:6) = 1,     1,     1,       ! CLASS PFT 2 BDL (BdlTr)  
!               EVG  DCD-CLD DCD-DRY  
modelpft(7:9)= 1,     1,     0,        ! CLASS PFT 3 CROP (Crop)  
!               C3      C4  
modelpft(10:12)= 1,     1,   1,   ! CLASS PFT 4 GRASS (Grass)  
!              C3      C4    sedges  
modelpft(13:15)= 1,     1,   0,   ! CLASS PFT 4 BDL SHRUB (BdlSh)  
!               EVG   DCD-CLD  

! List of CLASS-level PFTs  
classpfts = 'NdlTr' , 'BdlTr', 'Crops', 'Grass', 'BdlSh'  

! List of CTEM PFTs  
! **Note: 'BdlDCoTr' should be specified before 'BdlDDrTr' due to some code in competition.  
ctempfts = 'NdlEvgTr' , 'NdlDcdTr', 'BdlEvgTr','BdlDCoTr', 'BdlDDrTr','CropC3  ','CropC4  ','GrassC3 ','GrassC4 ','Sedge   ','BdlEvgSh','BdlDCoSh',  


In [135]:
ds.FCAN

<xarray.DataArray 'FCAN' (tile: 1, icp1: 5, lat: 1, lon: 1)>
array([[[[0.  ]],

        [[0.58]],

        [[0.  ]],

        [[0.42]],

        [[0.  ]]]])
Coordinates:
  * icp1     (icp1) int32 1 2 3 4 5
  * lat      (lat) float64 45.3
  * lon      (lon) float64 5.77
  * tile     (tile) int32 1
Attributes:
    units:      -
    long_name:  Annual maximum fractional coverage of modelled area (read in ...

In [37]:
with xr.set_options(keep_attrs=True):
    ds.FCAN[0, :, 0, 0] = 0
    ds.FCAN[0, 3, 0, 0] = 1.0
ds.FCAN

<xarray.DataArray 'FCAN' (tile: 1, icp1: 5, lat: 1, lon: 1)>
array([[[[0.]],

        [[0.]],

        [[0.]],

        [[1.]],

        [[0.]]]])
Coordinates:
  * icp1     (icp1) int32 1 2 3 4 5
  * lat      (lat) float64 45.3
  * lon      (lon) float64 5.77
  * tile     (tile) int32 1
Attributes:
    units:      -
    long_name:  Annual maximum fractional coverage of modelled area (read in ...

C3 -> Artic grass?  
C4 -> midlatitude grass

ctempfts = 'NdlEvgTr' , 'NdlDcdTr', 'BdlEvgTr','BdlDCoTr', 'BdlDDrTr','CropC3  ','CropC4  ','GrassC3 ','GrassC4 ','Sedge   ','BdlEvgSh','BdlDCoSh',


In [38]:
with xr.set_options(keep_attrs=True):
    ds.fcancmx[0, :, 0, 0] = 0
    ds.fcancmx[0, 8, 0, 0] = 1.0
ds.fcancmx

<xarray.DataArray 'fcancmx' (tile: 1, icctem: 9, lat: 1, lon: 1)>
array([[[[0.]],

        [[0.]],

        [[0.]],

        [[0.]],

        [[0.]],

        [[0.]],

        [[0.]],

        [[0.]],

        [[1.]]]])
Coordinates:
  * icctem   (icctem) int32 1 2 3 4 5 6 7 8 9
  * lat      (lat) float64 45.3
  * lon      (lon) float64 5.77
  * tile     (tile) int32 1
Attributes:
    units:      -
    long_name:  PFT fractional coverage per grid cell

In [138]:
ds

<xarray.Dataset>
Dimensions:          (ic: 4, iccp2: 11, icctem: 9, icp1: 5, lat: 1, layer: 20, lon: 1, slope: 8, tile: 1)
Coordinates:
  * ic               (ic) int32 1 2 3 4
  * iccp2            (iccp2) int32 1 2 3 4 5 6 7 8 9 10 11
  * icctem           (icctem) int32 1 2 3 4 5 6 7 8 9
  * icp1             (icp1) int32 1 2 3 4 5
  * lat              (lat) float64 45.3
  * layer            (layer) int32 1 2 3 4 5 6 7 8 9 ... 13 14 15 16 17 18 19 20
  * lon              (lon) float64 5.77
  * slope            (slope) int32 1 2 3 4 5 6 7 8
  * tile             (tile) int32 1
Data variables:
    ALBS             (tile, lat, lon) float64 0.5643
    ALIC             (tile, icp1, lat, lon) float64 0.0 0.0 0.0 0.0 0.0
    ALVC             (tile, icp1, lat, lon) float64 0.0 0.0 0.0 0.0 0.0
    CLAY             (tile, layer, lat, lon) float64 30.0 30.0 30.0 ... 0.0 0.0
    CMAS             (tile, ic, lat, lon) float64 0.0 0.0 0.0 0.0
    Cmossmas         (tile, lat, lon) float64 0.0
    DELZ             (layer) float64 0.1 0.1 0.1 0.1 0.1 ... 5.0 15.0 30.0 5.0
    DRN              (tile, lat, lon) float64 0.1
    FARE             (tile, lat, lon) float64 1.0
    FCAN             (tile, icp1, lat, lon) float64 0.0 0.0 0.0 1.0 0.0
    GC               (lat, lon) float64 -1.0
    GRO              (tile, lat, lon) float64 0.4285
    LNZ0             (tile, icp1, lat, lon) float64 0.0 0.0 0.0 0.0 0.0
    MID              (lat, lon) float64 1.0
    ORGM             (tile, layer, lat, lon) float64 0.0 0.0 0.0 ... 0.0 0.0 0.0
    PAMN             (tile, ic, lat, lon) float64 0.0 0.0 0.0 0.0
    PAMX             (tile, ic, lat, lon) float64 0.0 0.0 0.0 0.0
    RCAN             (tile, lat, lon) float64 0.0
    RHOS             (tile, lat, lon) float64 0.0
    ROOT             (tile, ic, lat, lon) float64 0.0 0.0 0.0 0.0
    SAND             (tile, layer, lat, lon) float64 60.0 60.0 ... -3.0 -3.0
    SCAN             (tile, lat, lon) float64 0.0
    SDEP             (tile, lat, lon) float64 3.5
    SNO              (tile, lat, lon) float64 0.0
    SOCI             (tile, lat, lon) float64 19.0
    TBAR             (tile, layer, lat, lon) float64 22.7 26.21 ... 12.61 12.61
    TCAN             (tile, lat, lon) float64 11.54
    THIC             (tile, layer, lat, lon) float64 0.0 0.0 0.0 ... 0.0 0.0 0.0
    THLQ             (tile, layer, lat, lon) float64 0.1392 0.1897 ... 0.0 0.0
    TPND             (tile, lat, lon) float64 0.0
    TSNO             (tile, lat, lon) float64 -273.2
    ZPND             (tile, lat, lon) float64 0.0
    bleafmas         (tile, icctem, lat, lon) float64 0.0 0.0 ... 0.01204
    dmoss            (tile, lat, lon) float64 0.0
    fcancmx          (tile, icctem, lat, lon) float64 0.0 0.0 0.0 ... 0.0 1.0
    gleafmas         (tile, icctem, lat, lon) float64 0.03069 0.0 ... 0.1243
    grclarea         (lat, lon) float64 100.0
    ipeatland        (tile, lat, lon) float64 0.0
    lfstatus         (tile, icctem, lat, lon) float64 1.0 4.0 1.0 ... 1.0 1.0
    litrmass         (tile, iccp2, lat, lon) float64 0.09167 0.0 ... 0.0 0.0
    litrmsmoss       (tile, lat, lon) float64 0.0
    nmtest           (lat, lon) float64 1.0
    pandays          (tile, icctem, lat, lon) float64 0.0 0.0 7.0 ... 7.0 7.0
    rootmass         (tile, icctem, lat, lon) float64 0.07974 0.0 ... 2.125
    slopefrac        (tile, slope, lat, lon) float64 0.0 0.0 0.0 ... 0.0 0.0 0.0
    soilcmas         (tile, iccp2, lat, lon) float64 0.5101 0.0 ... 0.0 0.0
    stemmass         (tile, icctem, lat, lon) float64 0.1253 0.0 ... 0.0 0.0
    maxAnnualActLyr  (tile, lat, lon) float64 61.4
    grwtheff         (tile, icctem, lat, lon) float64 100.0 100.0 ... 0.0 49.6
Attributes:
    title:          CLASSIC initialization file created from: /home/acrp001/m...
    creation_date:  20190523
    history:        Wed Jun 12 17:19:00 2019: ncks -4 ./rsfile.nc ./rsfile.nc
    NCO:            4.4.2
    row_bounds:     1 1

In [44]:
ds['SOCI'][0, 0, 0]

<xarray.DataArray 'SOCI' ()>
array(19.)
Coordinates:
    lat      float64 45.3
    lon      float64 5.77
    tile     int32 1
Attributes:
    units:      index
    long_name:  Soil colour index

In [45]:
with xr.set_options(keep_attrs=True):
    ds['SOCI'][0, 0, 0] = 15.
ds.SOCI

<xarray.DataArray 'SOCI' (tile: 1, lat: 1, lon: 1)>
array([[[15.]]])
Coordinates:
  * lat      (lat) float64 45.3
  * lon      (lon) float64 5.77
  * tile     (tile) int32 1
Attributes:
    units:      index
    long_name:  Soil colour index

In [46]:
ds.to_netcdf(path+'/AU-Tum_init_test.nc')
ds.to_netcdf(path+'/rsfile_test.nc')

In [115]:
ds

<xarray.Dataset>
Dimensions:          (ic: 4, iccp2: 11, icctem: 9, icp1: 5, lat: 1, layer: 20, lon: 1, slope: 8, tile: 1)
Coordinates:
  * ic               (ic) int32 1 2 3 4
  * iccp2            (iccp2) int32 1 2 3 4 5 6 7 8 9 10 11
  * icctem           (icctem) int32 1 2 3 4 5 6 7 8 9
  * icp1             (icp1) int32 1 2 3 4 5
  * lat              (lat) float64 45.3
  * layer            (layer) int32 1 2 3 4 5 6 7 8 9 ... 13 14 15 16 17 18 19 20
  * lon              (lon) float64 5.77
  * slope            (slope) int32 1 2 3 4 5 6 7 8
  * tile             (tile) int32 1
Data variables:
    ALBS             (tile, lat, lon) float64 0.5643
    ALIC             (tile, icp1, lat, lon) float64 0.0 0.0 0.0 0.0 0.0
    ALVC             (tile, icp1, lat, lon) float64 0.0 0.0 0.0 0.0 0.0
    CLAY             (tile, layer, lat, lon) float64 30.0 30.0 30.0 ... 0.0 0.0
    CMAS             (tile, ic, lat, lon) float64 0.0 0.0 0.0 0.0
    Cmossmas         (tile, lat, lon) float64 0.0
    DELZ             (layer) float64 0.1 0.1 0.1 0.1 0.1 ... 5.0 15.0 30.0 5.0
    DRN              (tile, lat, lon) float64 0.1
    FARE             (tile, lat, lon) float64 1.0
    FCAN             (tile, icp1, lat, lon) float64 0.0 0.0 0.0 1.0 0.0
    GC               (lat, lon) float64 -1.0
    GRO              (tile, lat, lon) float64 0.4285
    LNZ0             (tile, icp1, lat, lon) float64 0.0 0.0 0.0 0.0 0.0
    MID              (lat, lon) float64 1.0
    ORGM             (tile, layer, lat, lon) float64 0.0 0.0 0.0 ... 0.0 0.0 0.0
    PAMN             (tile, ic, lat, lon) float64 0.0 0.0 0.0 0.0
    PAMX             (tile, ic, lat, lon) float64 0.0 0.0 0.0 0.0
    RCAN             (tile, lat, lon) float64 0.0
    RHOS             (tile, lat, lon) float64 0.0
    ROOT             (tile, ic, lat, lon) float64 0.0 0.0 0.0 0.0
    SAND             (tile, layer, lat, lon) float64 60.0 60.0 ... -3.0 -3.0
    SCAN             (tile, lat, lon) float64 0.0
    SDEP             float64 3.4
    SNO              (tile, lat, lon) float64 0.0
    SOCI             int64 15
    TBAR             (tile, layer, lat, lon) float64 22.7 26.21 ... 12.61 12.61
    TCAN             (tile, lat, lon) float64 11.54
    THIC             (tile, layer, lat, lon) float64 0.0 0.0 0.0 ... 0.0 0.0 0.0
    THLQ             (tile, layer, lat, lon) float64 0.1392 0.1897 ... 0.0 0.0
    TPND             (tile, lat, lon) float64 0.0
    TSNO             (tile, lat, lon) float64 -273.2
    ZPND             (tile, lat, lon) float64 0.0
    bleafmas         (tile, icctem, lat, lon) float64 0.0 0.0 ... 0.01204
    dmoss            (tile, lat, lon) float64 0.0
    fcancmx          (tile, icctem, lat, lon) float64 0.0 0.0 0.0 ... 0.0 1.0
    gleafmas         (tile, icctem, lat, lon) float64 0.03069 0.0 ... 0.1243
    grclarea         (lat, lon) float64 100.0
    ipeatland        (tile, lat, lon) float64 0.0
    lfstatus         (tile, icctem, lat, lon) float64 1.0 4.0 1.0 ... 1.0 1.0
    litrmass         (tile, iccp2, lat, lon) float64 0.09167 0.0 ... 0.0 0.0
    litrmsmoss       (tile, lat, lon) float64 0.0
    nmtest           (lat, lon) float64 1.0
    pandays          (tile, icctem, lat, lon) float64 0.0 0.0 7.0 ... 7.0 7.0
    rootmass         (tile, icctem, lat, lon) float64 0.07974 0.0 ... 2.125
    slopefrac        (tile, slope, lat, lon) float64 0.0 0.0 0.0 ... 0.0 0.0 0.0
    soilcmas         (tile, iccp2, lat, lon) float64 0.5101 0.0 ... 0.0 0.0
    stemmass         (tile, icctem, lat, lon) float64 0.1253 0.0 ... 0.0 0.0
    maxAnnualActLyr  (tile, lat, lon) float64 61.4
    grwtheff         (tile, icctem, lat, lon) float64 100.0 100.0 ... 0.0 49.6
Attributes:
    title:          CLASSIC initialization file created from: /home/acrp001/m...
    creation_date:  20190523
    history:        Wed Jun 12 17:19:00 2019: ncks -4 ./rsfile.nc ./rsfile.nc
    NCO:            4.4.2
    row_bounds:     1 1

In [118]:
ds

<xarray.Dataset>
Dimensions:          (ic: 4, iccp2: 11, icctem: 9, icp1: 5, lat: 1, layer: 20, lon: 1, slope: 8, tile: 1)
Coordinates:
  * ic               (ic) int32 1 2 3 4
  * iccp2            (iccp2) int32 1 2 3 4 5 6 7 8 9 10 11
  * icctem           (icctem) int32 1 2 3 4 5 6 7 8 9
  * icp1             (icp1) int32 1 2 3 4 5
  * lat              (lat) float64 45.3
  * layer            (layer) int32 1 2 3 4 5 6 7 8 9 ... 13 14 15 16 17 18 19 20
  * lon              (lon) float64 5.77
  * slope            (slope) int32 1 2 3 4 5 6 7 8
  * tile             (tile) int32 1
Data variables:
    ALBS             (tile, lat, lon) float64 0.5643
    ALIC             (tile, icp1, lat, lon) float64 0.0 0.0 0.0 0.0 0.0
    ALVC             (tile, icp1, lat, lon) float64 0.0 0.0 0.0 0.0 0.0
    CLAY             (tile, layer, lat, lon) float64 30.0 30.0 30.0 ... 0.0 0.0
    CMAS             (tile, ic, lat, lon) float64 0.0 0.0 0.0 0.0
    Cmossmas         (tile, lat, lon) float64 0.0
    DELZ             (layer) float64 0.1 0.1 0.1 0.1 0.1 ... 5.0 15.0 30.0 5.0
    DRN              (tile, lat, lon) float64 0.1
    FARE             (tile, lat, lon) float64 1.0
    FCAN             (tile, icp1, lat, lon) float64 0.0 0.0 0.0 1.0 0.0
    GC               (lat, lon) float64 -1.0
    GRO              (tile, lat, lon) float64 0.4285
    LNZ0             (tile, icp1, lat, lon) float64 0.0 0.0 0.0 0.0 0.0
    MID              (lat, lon) float64 1.0
    ORGM             (tile, layer, lat, lon) float64 0.0 0.0 0.0 ... 0.0 0.0 0.0
    PAMN             (tile, ic, lat, lon) float64 0.0 0.0 0.0 0.0
    PAMX             (tile, ic, lat, lon) float64 0.0 0.0 0.0 0.0
    RCAN             (tile, lat, lon) float64 0.0
    RHOS             (tile, lat, lon) float64 0.0
    ROOT             (tile, ic, lat, lon) float64 0.0 0.0 0.0 0.0
    SAND             (tile, layer, lat, lon) float64 60.0 60.0 ... -3.0 -3.0
    SCAN             (tile, lat, lon) float64 0.0
    SDEP             float64 3.4
    SNO              (tile, lat, lon) float64 0.0
    SOCI             int64 15
    TBAR             (tile, layer, lat, lon) float64 22.7 26.21 ... 12.61 12.61
    TCAN             (tile, lat, lon) float64 11.54
    THIC             (tile, layer, lat, lon) float64 0.0 0.0 0.0 ... 0.0 0.0 0.0
    THLQ             (tile, layer, lat, lon) float64 0.1392 0.1897 ... 0.0 0.0
    TPND             (tile, lat, lon) float64 0.0
    TSNO             (tile, lat, lon) float64 -273.2
    ZPND             (tile, lat, lon) float64 0.0
    bleafmas         (tile, icctem, lat, lon) float64 0.0 0.0 ... 0.01204
    dmoss            (tile, lat, lon) float64 0.0
    fcancmx          (tile, icctem, lat, lon) float64 0.0 0.0 0.0 ... 0.0 1.0
    gleafmas         (tile, icctem, lat, lon) float64 0.03069 0.0 ... 0.1243
    grclarea         (lat, lon) float64 100.0
    ipeatland        (tile, lat, lon) float64 0.0
    lfstatus         (tile, icctem, lat, lon) float64 1.0 4.0 1.0 ... 1.0 1.0
    litrmass         (tile, iccp2, lat, lon) float64 0.09167 0.0 ... 0.0 0.0
    litrmsmoss       (tile, lat, lon) float64 0.0
    nmtest           (lat, lon) float64 1.0
    pandays          (tile, icctem, lat, lon) float64 0.0 0.0 7.0 ... 7.0 7.0
    rootmass         (tile, icctem, lat, lon) float64 0.07974 0.0 ... 2.125
    slopefrac        (tile, slope, lat, lon) float64 0.0 0.0 0.0 ... 0.0 0.0 0.0
    soilcmas         (tile, iccp2, lat, lon) float64 0.5101 0.0 ... 0.0 0.0
    stemmass         (tile, icctem, lat, lon) float64 0.1253 0.0 ... 0.0 0.0
    maxAnnualActLyr  (tile, lat, lon) float64 61.4
    grwtheff         (tile, icctem, lat, lon) float64 100.0 100.0 ... 0.0 49.6
Attributes:
    title:          CLASSIC initialization file created from: /home/acrp001/m...
    creation_date:  20190523
    history:        Wed Jun 12 17:19:00 2019: ncks -4 ./rsfile.nc ./rsfile.nc
    NCO:            4.4.2
    row_bounds:     1 1

In [140]:
ds.to_netcdf('FR_Cdp_init.nc')